version: '3.9'

services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf/hyperf:8.0-alpine-v3.13-swoole
    platform: linux/amd64
    working_dir: /app
    entrypoint: sh
    volumes:
      - ./:/app
    ports:
      - 9501:9501
    networks:
      - hyperf
  
networks:
  hyperf:
    driver: bridge
